jobs:
- job: Upload
  workspace:
    clean: all
  pool: 'Linux-CPU'
  condition: succeeded()
  steps:
  - checkout: self
    submodules: false

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact'
    inputs:
      artifactName: 'html'
      targetPath: '$(Build.BinariesDirectory)'
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 845
      buildVersionToDownload: specific
      pipelineId: 168696

  - task: CmdLine@2
    inputs:
      script: |
        python3 -m pip install pandas

  - task: AzureCLI@2
    displayName: 'Azure CLI'
    inputs:
      azureSubscription: AIInfraBuildOnnxRuntimeOSS
      scriptType: bash
      scriptPath: dddd
      inlineScript: $(Build.SourcesDirectory)/tools/ci_build/github/linux/upload_code_coverage_data.sh
      workingDirectory: '$(Build.BinariesDirectory)'

