jobs:
- job: Upload
  workspace:
    clean: all
  pool: 'Win-CPU-2021'
  condition: succeeded()
  steps:
  - checkout: self
    submodules: false

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact'
    inputs:
      artifactName: 'html'
      targetPath: '$(Build.BinariesDirectory)'
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 845
      buildVersionToDownload: specific
      pipelineId: 168696

  - task: AzureCLI@2
    displayName: 'Azure CLI '
    inputs:
      azureSubscription: AIInfraBuildOnnxRuntimeOSS
      scriptType: batch
      scriptLocation: inlineScript
      inlineScript: 'python3 $(Build.SourcesDirectory)/tools/ci_build/github/windows/post_code_coverage_to_dashboard.py --commit_hash=$(OnnxRuntimeGitCommitHash) --report_file="$(Build.BinariesDirectory)/report.json" --report_url="https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=$(Build.BuildId)" --branch $(Build.SourceBranchName) --arch $(Agent.OSArchitecture) --os $(Agent.OS) --build_config default'
      workingDirectory: '$(Build.BinariesDirectory)'

  - task: CmdLine@2
    inputs:
      script: |
        rm -f $(Build.BinariesDirectory)/report.json
      
  - task: AzureFileCopy@4
    displayName: 'AzureBlob File Copy'
    inputs:
      SourcePath: '$(Build.BinariesDirectory)\*'
      azureSubscription: AIInfraBuildOnnxRuntimeOSS
      Destination: AzureBlob
      storage: onnxruntime
      ContainerName: '$web'
