parameters:
  AgentPool: 'Linux-CPU'
  ArtifactSuffix: ''
  NugetPackageName : ''

jobs:
- job: NuGet_Test_Linux_${{ parameters.ArtifactSuffix }}
  workspace:
    clean: all
  timeoutInMinutes:  120
  pool: ${{ parameters.AgentPool }}
  condition: succeeded()
  variables:
  - name: OnnxRuntimeBuildDirectory
    value: '$(Build.BinariesDirectory)'
  steps:

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Signed NuGet'
    inputs:
      artifactName: drop-signed-nuget-${{ parameters.ArtifactSuffix }}
      targetPath: '$(Build.BinariesDirectory)/nuget-artifact'
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 940
      buildVersionToDownload: specific
      pipelineId: 168417

  - task: DownloadPipelineArtifact@0
    displayName: 'Download Linux CustomOp TestData'
    inputs:
      artifactName: 'drop-linux'
      targetPath: '$(Build.BinariesDirectory)/testdata'
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 940
      buildVersionToDownload: specific
      pipelineId: 168417

  - template: get-nuget-package-version-as-variable.yml
    parameters:
      packageFolder: '$(Build.BinariesDirectory)/nuget-artifact'

  - task: CmdLine@2
    displayName: 'Create symlink for test models'
    inputs:
      script: |     
         ln -sf /data/models $(Build.BinariesDirectory)

  - task: Bash@3
    displayName: 'Run Package Test'
    inputs:
      targetType: filePath
      filePath: '$(Build.SourcesDirectory)/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests/runtest.sh'
      arguments: '$(Build.BinariesDirectory)/nuget-artifact $(NuGetPackageVersionNumber)'
      workingDirectory: $(Build.BinariesDirectory)
    env:
      OnnxRuntimeBuildDirectory: $(Build.BinariesDirectory)
      DisableContribOps: $(DisableContribOps)
      DisableMlOps: $(DisableMlOps)
      IsReleaseBuild: $(IsReleaseBuild)
      PACKAGENAME: ${{ parameters.NugetPackageName }}
        
  - template: ../../templates/component-governance-component-detection-steps.yml
    parameters :
      condition : 'always'

  - template: ../../templates/clean-agent-build-directory-step.yml
